services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  barcode.storage.hash.default:
      public: true
      class: Nkamuo\Barcode\Storage\InMemoryHashStorage
      tags:
          - name: barcode.storage
          - name: barcode.storage.hash
