services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  barcode.decoder.gs1.qrcode:
      public: true
      class: Nkamuo\Barcode\Decoder\GS1\GS1SimpleBarcodeDecoder
      tags:
          - name: barcode.decoder
          - name: barcode.decoder
            processor: gs1

  barcode.decoder.gs1.complex_barcode:
      public: true
      class: Nkamuo\Barcode\Decoder\GS1\GS1ComplexBarcodeDecoder
      tags:
        - name: barcode.decoder
        - name: barcode.decoder
          processor: gs1
