services:
    barcode.encoder.gs1.qrcode:
      public: true
      class: Nkamuo\Barcode\Encoder\GS1QRCodeEncoder
      tags:
          - name: barcode.encoder
          - name: barcode.encoder
            processor: gs1

    barcode.encoder.gs1.complex_barcode:
      public: true
      class: Nkamuo\Barcode\Encoder\GS1ComplexBarcodeEncoder
      tags:
        - name: barcode.encoder
        - name: barcode.encoder
          processor: gs1
