services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  barcode.encoder.gs1.qrcode:
      public: true
      class: Nkamuo\Barcode\Encoder\GS1\GS1QRCodeEncoder
      tags:
          - name: barcode.encoder
          - name: barcode.encoder
            processor: gs1

  barcode.encoder.gs1.complex_barcode:
      public: true
      class: Nkamuo\Barcode\Encoder\GS1\GS1ComplexBarcodeEncoder
      tags:
        - name: barcode.encoder
        - name: barcode.encoder
          processor: gs1
