services:
    barcode.formatter.gs1.data:
      class: Nkamuo\Barcode\Formatter\DataBarcodeFormatter
      tags:
          - name: barcode.formatter
          - name: barcode.formatter
            processor: gs1

    barcode.formatter.gs1.readable_label:
      class: Nkamuo\Barcode\Formatter\ReadableLabelBarcodeFormatter
      tags:
        - name: barcode.formatter
        - name: barcode.formatter
          processor: gs1
